export const ADD_NEW_CONTACT = "ADD_NEW_CONTACT";
export const SEARCH_IS_EMPTY_TOGGLE = "SEARCH_IS_EMPTY_TOGGLE";
export const SET_FILTERED_LIST = "SET_FILTERED_LIST";
export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SET_NEW_CONTACT_LIST = "SET_NEW_CONTACT_LIST";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
